### ISSUE TITLE
Error using notebook_shim with jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by scmmmh** [jupyter/notebook_shim#9]
I'm trying to use nbclassic (0.4.2.) with the [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) using the notebook_shim and getting the following error:

```
[I 2022-07-07 13:15:54.243 ServerApp] notebook_shim | extension was successfully loaded.
[D 2022-07-07 13:15:54.243 ServerApp] [jupyter_nbextensions_configurator] Loading 0.4.1
[D 2022-07-07 13:15:54.243 ServerApp] [jupyter_nbextensions_configurator]   Editing templates path to add /usr/local/lib/python3.9/site-packages/jupyter_nbextensions_configurator/templates
[D 2022-07-07 13:15:54.243 ServerApp] [jupyter_nbextensions_configurator]   Editing nbextensions path to add /usr/local/lib/python3.9/site-packages/jupyter_nbextensions_configurator/static
[D 2022-07-07 13:15:54.243 ServerApp] Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 351, in load_extension
        extension.load_all_points(self.serverapp)
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 231, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 231, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 224, in load_point
        return point.load(serverapp)
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 150, in load
        return loader(serverapp)
      File "/usr/local/lib/python3.9/site-packages/jupyter_nbextensions_configurator/__init__.py", line 247, in load_jupyter_server_extension
        if static_files_path not in webapp.settings['nbextensions_path']:
    KeyError: 'nbextensions_path'
    
[W 2022-07-07 13:15:54.243 ServerApp] jupyter_nbextensions_configurator | extension failed loading with message: 'nbextensions_path'
```

**Comment by dleen** [comment]
Also having this issue - will see if I can track it down!

**Comment by dleen** [comment]
So there's a fix for this exception here: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/141 and it's waiting on the nbextensions_configurator team to merge it.

However even after I add that patch locally nbextensions_configurator doesn't quite work - still get a bunch of 404s:
```
404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js
```
but at least no stack traces. I'm not sure if this is the right place for this issue.

**Comment by dleen** [comment]
Would recommend closing this and tracking the nbextensions PR.

**Comment by dleen** [comment]
Oh to get the configurator working with nbclassic:
```
$ pip install jupyter_nbextensions_configurator
$ jupyter nbextension install --sys-prefix --py jupyter_nbextensions_configurator --overwrite
$ jupyter nbextension enable --sys-prefix --py jupyter_nbextensions_configurator
$ jupyter serverextension enable --sys-prefix --py jupyter_nbextensions_configurator
```

from: https://github.com/jupyter/nbclassic/blob/main/docs/source/nbclassic_dev_faq.rst#known-issues

We're all set here :)
